name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Replace token in app.js
      run: |
        sed -i "s/let GITHUB_TOKEN = localStorage.getItem('github_token') || '';/let GITHUB_TOKEN = '${{ secrets.GIST_TOKEN }}';/" app.js
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add app.js
        git commit -m "Auto-inject token [skip ci]" || echo "No changes to commit"
        git push